# Site settings
# the baseURL should end with a slash /
# baseURL = "http://faculty.chemeketa.edu/nmitche6/precalculus/"
baseURL = "https://duragauge.github.io"
publishDir = "docs"
# if you are publishing to the root directory of your site, set canonifyURLs to "false", otherwise keep it "true"
canonifyURLs = "true"
languageCode = "en-us"
title = "Precalculus 1 - Functions"
theme = "forty"


[outputs]
home = [ "HTML"]


# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
  [markup]
    defaultMarkdownHandler = "goldmark"
    [markup.blackFriday]
      angledQuotes = false
      footnoteAnchorPrefix = ""
      footnoteReturnLinkContents = ""
      fractions = false
      hrefTargetBlank = true
      latexDashes = true
      nofollowLinks = false
      noreferrerLinks = false
      plainIDAnchors = true
      skipHTML = false
      smartDashes = false
      smartypants = false
      smartypantsQuotesNBSP = false
      taskLists = true
      extensions = ["backslashLineBreak"]
    [markup.goldmark]
      [markup.goldmark.extensions]
        definitionList = true
        footnote = true
        linkify = true
        strikethrough = true
        table = true
        taskList = true
        typographer = false
      [markup.goldmark.parser]
        attribute = true
        autoHeadingID = true
        autoHeadingIDType = "github"
      [markup.goldmark.renderer]
        hardWraps = false
        unsafe = true
        xhtml = false
    [markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      noClasses = true
      style = "monokai"
      tabWidth = 4
    [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2


[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Nolan Mitchell"
  description = "A book about precalculus"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Precalculus"
    subtitle = "Functions"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

#    [[params.navigation.links]]
#      name = "Home"
#      url = "#"

#    [[params.navigation.links]]
#      name = "Blogs"
#      url = "blogs"


    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Home"
      url = "#"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Search"
      url = "search"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "College Algebra"
    subtitle = "An attempt at making a book."
    buttonText = "Scroll down"


  # create a chapter parameter for use when compiling full-chapters
  [params.chapter]


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

#    [[params.tiles.showcase]]
#      title = "Chapter 0"
#      subtitle = "Foundations of Algebra"
#      image = "chapter-0-header.jpg"
#      url = "chapter-0"

    [[params.tiles.showcase]]
      title = "Chapter 1"
      subtitle = "Functions"
      image = "chapter-1-header.jpg"
      url = "chapter-1"

    [[params.tiles.showcase]]
      title = "Chapter 2"
      subtitle = "Power Functions"
      image = "chapter-2-header.jpg"
      url = "chapter-2"

    [[params.tiles.showcase]]
      title = "Chapter 3"
      subtitle = "Exponentials Functions"
      image = "chapter-3-header.jpg"
      url = "chapter-3"

    [[params.tiles.showcase]]
      title = "Chapter 4"
      subtitle = "Combining Functions"
      image = "chapter-4-header.jpg"
      url = "chapter-4"

    [[params.tiles.showcase]]
      title = "Chapter 5"
      subtitle = "Polynomial Functions"
      image = "chapter-5-header.jpg"
      url = "chapter-5"

    [[params.tiles.showcase]]
      title = "Chapter 6"
      subtitle = "Modeling with Functions"
      image = "chapter-6-header.jpg"
      url = "chapter-6"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more information take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About"
    subtitle = "This textbook was developed by Nolan Mitchell for the MTH111Z Precalculus 1: Functions course at Chemeketa Community College. All content, including text, equations, figures, and interactive elements, is available under a non-commercial Creative Commons license and was created with freely available software. Equations are written in LaTeX and rendered through MathJax. Photos, most requiring no attribution, are linked to their sources.  Interactive figures were crafted using GeoGebra.  All other graphics were designed by the author using Inkscape and Gimp. The entire book was compiled using the Hugo static site generator from Markdown files within Visual Studio, incorporating the forty theme and Tufte styles."

#    buttonText = "Get Started"
#    url = "blogs"


  # Contact section
  [params.contact]
    enable = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = ""



    [[params.footer.quicklinks]]
      text = "Deign: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
